#Make sure to replace ${GITPOD_REPO_ROOT} with the actual root directory of your 
image:
  file: .gitpod.Dockerfile

ports:
  - port: 7123
    onOpen: ignore
  - port: 7357
    onOpen: ignore

tasks:
  - init: bash devcontainer_bootstrap
    command: sleep infinity
    name: Example devcontainer for add-on repositories

vscode:
  extensions:
    - timonwong.shellcheck
    - esbenp.prettier-vscode

plugins:
  vscode:
    terminal.integrated.profiles.linux:
      zsh:
        path: /usr/bin/zsh
    terminal.integrated.defaultProfile.linux: zsh
    editor.formatOnPaste: false
    editor.formatOnSave: true
    editor.formatOnType: true
    files.trimTrailingWhitespace: true

workspace:
  - name: Home Assistant Add-ons
    location: "${GITPOD_REPO_ROOT}"
    mount:
      type: volume
      source: "${GITPOD_REPO_ROOT}"
      target: /var/lib/docker
