# Homeassistant configuration
# Use "Update HA config" task to use this configuration instead of default one
# required for running in codespaces
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

#enable proxy so that we can run this in codespaces
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
